//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante_WLDM
    {
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Id { get; set; }
        public string Telefono { get; set; }
        public string Edad { get; set; }
    }
}
